name: Release Preview Nuget Package

on:
  push:
    branches: [ dev ]

jobs:
  release-preview:
   if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
   runs-on: ubuntu-latest

   steps:
   - uses: actions/checkout@v4
   - uses: benjlevesque/short-sha@v2.2
     id: short-sha
   - name: Setup .NET
     uses: actions/setup-dotnet@v3
     with:
       dotnet-version: 6.0.x
   - name: Restore dependencies
     run: dotnet restore
   - name: Build TwitchLib.Api
     run: dotnet build -c Release --no-restore
   - name: Pack TwitchLib.Api
     run: dotnet pack TwitchLib.Api.sln -v normal -c Release -o nugets --no-build --version-suffix "preview-${{ steps.short-sha.outputs.sha }}"
   - name: Push to Nuget
     run: dotnet nuget push "./nugets/*.nupkg" -k ${{ secrets.API_NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
   - name: Send Discord Notification
     uses: sarisia/actions-status-discord@v1
     if: always()
     with:
       webhook: ${{ secrets.DISCORD_WEBHOOK }}
       title: "Release Preview Nuget Package"
       username: "TwitchLib Deploy"
