name: Release Preview Nuget Package

on:
  push:
    branches: [ dev ]

jobs:
  release-preview:
   if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
   runs-on: ubuntu-latest
   permissions:
      id-token: write  # enable GitHub OIDC token issuance for this job

   steps:
   - uses: actions/checkout@v5
   - uses: benjlevesque/short-sha@v3.0
     id: short-sha
   - name: Setup .NET
     uses: actions/setup-dotnet@v5
     with:
       dotnet-version: 8.0.x
   - name: Restore dependencies
     run: dotnet restore
   - name: Build TwitchLib.Api
     run: dotnet build -c Release --no-restore
   - name: Pack TwitchLib.Api
     run: dotnet pack TwitchLib.Api.sln -v normal -c Release -o nugets --no-build --version-suffix "preview.${{ github.run_number }}.${{ steps.short-sha.outputs.sha }}"
    # Get a short-lived NuGet API key
   - name: NuGet login (OIDC â†’ temp API key)
     uses: NuGet/login@v1
     id: login
     with:
       user: ${{ secrets.NUGET_USER }}
   - name: Push to Nuget
     run: dotnet nuget push "./nugets/*.nupkg" --api-key ${{steps.login.outputs.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
   - name: Send Discord Notification
     uses: sarisia/actions-status-discord@v1
     if: always()
     with:
       webhook: ${{ secrets.DISCORD_WEBHOOK }}
       title: "Release Preview Nuget Package"
       username: "TwitchLib Deploy"
